# Generated by Django 3.1.2 on 2020-10-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of picture')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, default='', upload_to='images/pictures', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
                'ordering': ['name'],
            },
        ),
    ]
