# Generated by Django 3.1.2 on 2020-10-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of MainPicture')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('main_picture', models.ImageField(upload_to='images/mainpicture', verbose_name='Main picture')),
            ],
            options={
                'verbose_name': 'MainPicture',
                'verbose_name_plural': 'MainPictures',
            },
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to='images/pictures', verbose_name='Picture'),
        ),
    ]
