# Generated by Django 3.1.2 on 2020-10-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201014_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=60, verbose_name='Name, Surname')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('Photo', models.ImageField(upload_to='images/photo', verbose_name='Photo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mainpicture',
            options={'verbose_name': 'Главная картинка', 'verbose_name_plural': 'Главная картинка'},
        ),
        migrations.AlterModelOptions(
            name='pictures',
            options={'ordering': ['name'], 'verbose_name': 'список картинок', 'verbose_name_plural': 'список картинок'},
        ),
    ]
