# Generated by Django 3.1.2 on 2020-10-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201015_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='Photo',
            new_name='photo',
        ),
    ]
