# Generated by Django 3.1.2 on 2020-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201015_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(max_length=600, verbose_name='Description'),
        ),
    ]
