# Generated by Django 3.1.2 on 2020-10-16 09:13

from django.db import migrations
import django.utils.timezone
import django_ckeditor_5.fields
import djrichtextfield.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201016_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='text1',
            field=djrichtextfield.models.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text2',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text3',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
