# Generated by Django 3.1.2 on 2020-10-30 15:11

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20201030_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='text2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now, verbose_name='RichTextUploadingField'),
            preserve_default=False,
        ),
    ]
