# Generated by Django 3.1.2 on 2020-10-30 15:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_testimonial_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='text',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text2',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
